In [39]:
from numpy import *
from numpy.linalg import norm, det, trace, inv, pinv, eigh, eig

d, N = 3, 5

A = N * outer( arange(d), ones(N) ) + outer( ones(d), 1+arange(N) )

Q = dot(A, A.T)
a,b,c,d,e = A.T
A, Q

(array([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]]),
 array([[ 55., 130., 205.],
        [130., 330., 530.],
        [205., 530., 855.]]))

In [53]:

g = array([0,1,2])
f = array([54,77,100])
B = column_stack([f,g])
Bminus = pinv(B)
S = dot(Bminus, dot(Q,B))

lamda, U = eig(S)

u = array([[1,delta],[1,-delta]])

U/U[0,0], delta

(array([[ 1.        , -1.        ],
        [61.39218191, 61.39218191]]),
 np.float64(61.39218191268331))

In [37]:
S = array([[250, 10],
       [24000, 990]])

u = array([1,-1])

eig(S)

EigResult(eigenvalues=array([   6.07818087, 1233.92181913]), eigenvectors=array([[-0.04096233, -0.01016288],
       [ 0.99916069, -0.99994836]]))

In [38]:
from numpy import around

delta = sqrt(3769)
lamda1 = 620+10*delta
lamda2 = 620-10*delta

S, lamda1, lamda2, dot(S,u), lamda1*u

(array([[  250,    10],
        [24000,   990]]),
 np.float64(1233.9218191268333),
 np.float64(6.078180873166843),
 array([  240, 23010]),
 array([ 1233.92181913, -1233.92181913]))

In [60]:
delta = sqrt(3769)

u1 = f - delta* g 
u1 = u1 /norm(u1)
lamda1 = 620-10*delta

u2 = f + delta* g
u2 = u2/norm(u2)
lamda2 = 620+10*delta

v1 = dot(A.T,u1)
v2 = dot(A.T,u2)
v1 = v1/norm(v1)
v2 = v2/norm(v2)

u = array([u1,u2])
v = array([v1,v2])
lamda = array([lamda1,lamda2])
sigma = sqrt(lamda)

C = sum( [ a*outer(b,c) for a,b,c in zip(1/sigma,v,u) ], axis = 0)
round(150*C,2)

array([[-37., -10.,  17.],
       [-20.,  -5.,  10.],
       [ -3.,  -0.,   3.],
       [ 14.,   5.,  -4.],
       [ 31.,  10., -11.]])

In [ ]:
sum 

In [49]:
r, s, t = dot(f,f), dot(f,g), dot(g,g)
N = array([[r,s],[s,t]])

r, s, t

(np.float64(18845.0), np.float64(277.0), np.int64(5))

In [50]:
c = det(M)/det(N)
c

np.float64(7500.000000000254)

In [51]:
b = trace( dot(M,inv(N)))
b

np.float64(1240.0000000000005)

In [52]:
Bminus = pinv(B)
Bminus

array([[ 0.0154321 ,  0.00617284, -0.00308642],
       [-0.85493827, -0.14197531,  0.57098765]])

In [53]:
S = dot(Bminus, dot(Q, B))

S



array([[6.200e+02, 1.000e+01],
       [3.769e+04, 6.200e+02]])

In [287]:
u1 = f + delta*g
u2 = f - delta*g



array([[-37., -10.,  17.],
       [-20.,  -5.,  10.],
       [ -3.,  -0.,   3.],
       [ 14.,   5.,  -4.],
       [ 31.,  10., -11.]])

In [27]:
from sympy import *

Bsym = Matrix([[ 54,   0],
       [ 77,   1],
       [100,   2]])

Bsym.pinv()

Matrix([
[   5/324,   1/162,  -1/324],
[-277/324, -23/162, 185/324]])

In [205]:
Ssym.eigenvects()

[(620 - 10*sqrt(3769),
  1,
  [Matrix([
   [23/54 - sqrt(3769)/54],
   [                    1]])]),
 (10*sqrt(3769) + 620,
  1,
  [Matrix([
   [23/54 + sqrt(3769)/54],
   [                    1]])])]

In [209]:
delta = 3769

In [210]:
f1 = array([23, 54])
g1 =array([1,0])

u = f1 + delta * g1
u

array([3792,   54])

In [211]:
dot(S, u), u

TypeError: unsupported operand type(s) for *: 'SingletonRegistry' and 'int'

In [ ]:
Bsym 