In [1]:
from numpy import *

from numpy.random import default_rng as rng
samples = rng().random

#dxN matrix

d = 3
N = 5

f = samples((d,))
g = samples((d,))
p = samples((N,))
q = samples((N,))

A = outer(f,p) + outer(g,q)
A

array([[0.41004331, 0.12559628, 0.17301998, 0.10372127, 0.45444436],
       [0.19398689, 0.18076661, 0.22681443, 0.14386683, 0.33752525],
       [1.04434257, 0.66265307, 0.85013386, 0.53194136, 1.50354415]])

In [6]:

Q = dot(A.T, A)
tr = Q.trace()
tr

np.float64(5.483591552348061)

In [9]:
from numpy.linalg import eigh

lamda, U = eigh(Q)
lamda[-1] * lamda[-2]

np.float64(0.15200081108329)

In [3]:
Qprime = Q - tr* eye(N)/2
Qprime

array([[-1.44537795,  0.77860308,  1.00277568,  0.62596749,  1.8220325 ],
       [ 0.77860308, -2.25423569,  0.62607495,  0.3915259 ,  1.11441797],
       [ 1.00277568,  0.62607495, -1.93768751,  0.50279828,  1.43339734],
       [ 0.62596749,  0.3915259 ,  0.50279828, -2.4273784 ,  0.89549155],
       [ 1.8220325 ,  1.11441797,  1.43339734,  0.89549155, -0.16070779]])

In [10]:
from numpy.linalg import norm, eigh

u = 10*p - sqrt(2)*q

a = norm(dot(Qprime, u))
b = norm(u)

delta = a/b

(tr/2)**2 - delta**2

np.float64(0.152000811083286)

In [15]:

lamda, U = eigh(Q)
lamda

array([-6.65217812e-17, -4.92099352e-17,  1.64409006e-16,  1.41311102e-02,
        2.21573099e+00])

In [11]:
solve(p)

[]